pubnub/react-chat-components

- lib/docs/stories/introduction/usage.stories.mdx
> Typo in Component

- lib/docs/stories/introduction/metadata.stories.mdx
> Typo in feature

- lib/docs/stories/introduction/usage.stories.mdx
- samples/group-chat/README.md
This change relates to the issue https://pubnub.atlassian.net/browse/UI-814.
> docs: gs add info on verifying the app is connected

- lib/docs/stories/introduction/usage.stories.mdx
Storage & Playback feature name changed to Message Persistence
> Storage & Playback feature name change

- .pubnub.yml
- lib/docs/preview.js
- lib/docs/stories/components/ChannelList.stories.tsx
- lib/docs/stories/components/MemberList.stories.tsx
- lib/mock/pubnub-mock.ts
- lib/package-lock.json
- lib/package.json
- lib/rollup.config.js
- lib/test/channel-list.test.tsx
- lib/test/member-list.test.tsx
- lib/test/message-input.test.tsx
- samples/getting-started/package-lock.json
- samples/group-chat/package-lock.json
- samples/group-chat/package.json
- samples/group-chat/populate-pn-objects.js
- samples/group-chat/src/index.tsx
- samples/live-events/package-lock.json
- samples/live-events/package.json
- samples/live-events/src/components/ChatView.tsx
- samples/live-events/src/index.tsx
- samples/simple-chat/package-lock.json
- samples/simple-chat/package.json
- samples/simple-chat/src/index.tsx
- samples/simple-chat/src/simple-chat.tsx
- samples/telehealth/package-lock.json
- samples/telehealth/package.json
- samples/telehealth/src/index.tsx
fix: MessageInput - user metadata not attached to File messages with senderInfo option enabled
fix: Channel/MemberList - disable default flex shrinking of some UI elements (e.g. avatars)
> release: v0.10.0

- samples/live-events/package-lock.json
- samples/live-events/package.json
- yarn.lock
…thin iFrame in incognito mode.
There was a specific set of circumstances which would cause the app to crash, caused by my pubnub-demo-integration plugin.  This is only an issue when running the demo in an iFrame with the browser in incognito mode.  This pull request fixes that issue by updating the pubnub-demo-integration plugin.
> chore: update demo integration in live-events sample

- lib/package-lock.json
- lib/package.json
- lib/src/helpers.ts
- lib/src/message-list/message-list.scss
- lib/src/message-list/message-list.tsx
- lib/test/message-list.test.tsx
fix: MessageList - non intended auto scrolling of parent elements
> fix: auto scroll of MessageList in a scrollable view

- .github/workflows/release.yml
- .github/workflows/release/versions.json
build(workflows): utilise new action features
Because multiple artefacts will released, they should be archived separately.
> Utilise new action features

- .pubnub.yml
- packages/common/package.json
- packages/react-native/package.json
- packages/react/package.json
- samples/react-native/getting-started/src/getting-started-react-native.tsx
- samples/react-native/mobile-chat/App.tsx
- samples/react/getting-started/src/getting-started.tsx
- samples/react/group-chat/src/index.tsx
- samples/react/live-events/src/index.tsx
- samples/react/telehealth/src/index.tsx
feat: Initial release for React Native components package
> release: v0.14.0

- .github/workflows/on-pull-request-create.yml
- .github/workflows/release/reviewers.json
- packages/react/src/member-list/member-list.tsx
build(reviewers): add automated reviewers assigner
Add automated reviewers assignment action usage.
> Add automated reviewers assigner

- .pubnub.yml
- packages/common/package.json
- packages/common/src/message-list/message-list.tsx
- packages/react-native/package.json
- packages/react/package.json
fix: MessageList - Include meta data for historic messages
> fix(lib): fetch metadata for message history

- samples/react/group-chat/package.json
- samples/react/group-chat/public/features.json
- samples/react/group-chat/src/moderated-chat.tsx
- yarn.lock
Adding features for the interactive demo, hosted at https://www.pubnub.com/demos/group-chat-react-demo/
**Plan is:**
1. Add interactive features to this repository (addressed by this pull request)
2. Publish updates to https://react-components-chat.pubnub.com/ (I presume this is the correct URL for the hosted version of this repo)
3. Update https://www.pubnub.com/demos/group-chat-react-demo/ to point to https://react-components-chat.pubnub.com/
4. Delete https://github.com/PubNubDevelopers/React-Group-Chat-Demo
> feat(samples): add features for interactive demo in group chat

- .github/workflows/run-tests.yml
This commit contains changes in CI/CD configuration for e2e tests. Temporary branch was changed to master branch.
> e2e tests run branch reconfigured to master branch

- .pubnub.yml
- packages/common/package.json
- packages/common/src/chat/chat.tsx
- packages/common/src/message-list/message-list.tsx
- packages/common/src/state-atoms.ts
- packages/react-native/package.json
- packages/react-native/test/message-list.test.tsx
- packages/react/package.json
- packages/react/test/message-list.test.tsx
- samples/react/group-chat/src/moderated-chat.tsx
feat: ReactNative - added file upload functionality
feat: Chat - added getUser callback to load user's metadata when first seen
> feat(lib): load users when seen pattern implementation

- .pubnub.yml
- packages/common/package.json
- packages/common/src/typing-indicator/typing-indicator.tsx
- packages/react-native/package.json
- packages/react/package.json
fix: fix not being able to click on emojis on the last message of the Message List
> feat(lib): change import order

- .pubnub.yml
- packages/common/package.json
- packages/common/src/message-input/message-input.tsx
- packages/react-native/package.json
- packages/react-native/src/message-input/message-input.tsx
- packages/react/package.json
- packages/react/src/message-input/message-input.tsx
- packages/react/test/message-input.test.tsx
feat: return change event and expose onKeyPress callback
> feat(lib): return change event and expose onKeyPress callback

- .pubnub.yml
- packages/common/package.json
- packages/react-native/package.json
- packages/react/package.json
- packages/react/src/message-input/message-input.tsx
feat: remove a warning about missing onKeyPress
> fix(lib): remove a warning about missing onKeyPress

- .pubnub.yml
- packages/common/package.json
- packages/react-native/package.json
- packages/react-native/rollup.config.js
- packages/react/package.json
feat: ReactNative - Fix uuid not being bundled correctly
> fix(lib): fix RN uuid

- .pubnub.yml
- packages/common/package.json
- packages/react-native/package.json
- packages/react/package.json
- packages/react/src/message-input/message-input.tsx
feat: MessageInput - allow passing default input field attributes
feat: MessageInput - new sendMessageOnSubmitEditing option in React Native
feat: MessageInput - focus on the field after selecting emoji in React
> release: v0.29

- .pubnub.yml
- packages/common/package.json
- packages/common/src/message-input/message-input.tsx
- packages/react-native/package.json
- packages/react-native/src/message-input/message-input.tsx
- packages/react/package.json
- packages/react/src/message-input/message-input.tsx
fix: focusing on EmojiInput after selecting emoji only worked in certain cases
fix: console warnings about unknown attributes in MessageInput
> fix: focusing on MessageInput after selecting emoji

- .pubnub.yml
- packages/common/package.json
- packages/common/src/message-input/message-input.tsx
- packages/react-native/package.json
- packages/react-native/src/message-input/message-input.style.ts
- packages/react-native/src/message-input/message-input.tsx
- packages/react/package.json
- packages/react/src/message-input/message-input.scss
- packages/react/src/message-input/message-input.tsx
- packages/react/test/message-input.test.tsx
feat: make it possible to send both text and file in one message
> Add file + text upload capabilities

- .github/workflows/run-tests.yml
- .pubnub.yml
- load-tests/react-native/package.json
- packages/common/package.json
- packages/react-native/package.json
- packages/react-native/src/message-list/android-hack-workaround.native.ts
- packages/react-native/src/message-list/android-hack-workaround.ts
- packages/react-native/src/message-list/message-list.tsx
- packages/react/package.json
- samples/react-native/getting-started/package.json
- samples/react-native/mobile-chat/package.json
- yarn.lock
fix: ReactNative - remove the workaround for poor performance of inverted FlatList in Android
> fix(lib): remove inverted flatlist fix for android

- .pubnub.yml
- packages/common/package.json
- packages/common/src/hooks/use-channel-members.ts
- packages/common/src/hooks/use-channels.ts
- packages/common/src/hooks/use-presence.ts
- packages/common/src/hooks/use-user-memberships.ts
- packages/common/src/hooks/use-user.ts
- packages/common/src/hooks/use-users.ts
- packages/common/src/message-input/message-input.tsx
- packages/common/test/use-channel-members.test.tsx
- packages/common/test/use-channels.test.tsx
- packages/react-native/package.json
- packages/react/package.json
- packages/react/src/message-list/message-item.tsx
feat: expose "isLoading" flags to hooks
> feat(lib): react to changes in users atom and expose loading flags
